apiVersion: apps/v1
kind: Deployment
metadata:
  name: vldapi-deployment
spec:
  selector:
    matchLabels:
      app: vldapi-app
  template:
    metadata:
      labels:
        app: vldapi-app
    spec:
      containers:
      - name: vldapi-container
        image: jorgeabrego/vld-api:v0.1.2
        imagePullPolicy: Always
        ports:
        - containerPort: 8000