name: CI for Dev

on:
  push:
    branches:
      - develop
    paths:
      - app/**
  pull_request:
    branches:
      - develop
    paths:
      - app/**

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8 pytest

    - name: Lint code
      run: |
        flake8 app

    - name: Run tests
      run: |
        pytest