name: Build Docker Image on Tag

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Validate tag is on main branch
      run: |
        git fetch origin main
        MAIN_COMMIT=$(git rev-parse origin/main)
        TAG_COMMIT=$(git rev-parse ${GITHUB_SHA})

        if [ "$MAIN_COMMIT" != "$TAG_COMMIT" ]; then
          echo "Tag is not associated with the main branch. Exiting."
          exit 1
        fi

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and push Docker image (multi-archs)
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          jorgeabrego/vld-api:latest
          jorgeabrego/vld-api:${{ github.ref_name }}
